// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TDD_StreamingSearch
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CustomerFeaturesFeature : Xunit.IClassFixture<CustomerFeaturesFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "customerFeatures.feature"
#line hidden
        
        public CustomerFeaturesFeature(CustomerFeaturesFeature.FixtureData fixtureData, TDD_StreamingSearch_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "customerFeatures", "\tI want to know where I can stream a show or movie in my region", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Find streaming sites in my region which have the show I want to watch")]
        [Xunit.TraitAttribute("FeatureTitle", "customerFeatures")]
        [Xunit.TraitAttribute("Description", "Find streaming sites in my region which have the show I want to watch")]
        [Xunit.TraitAttribute("Category", "findShowInMyRegion")]
        [Xunit.InlineDataAttribute("The Young Ones", "UK", "matt.barbier@os.uk", "Disney plus, Netflix", "false", new string[0])]
        [Xunit.InlineDataAttribute("Rick and Morty", "UK", "mike.bruce@os.uk", "Now Tv", "true", new string[0])]
        public virtual void FindStreamingSitesInMyRegionWhichHaveTheShowIWantToWatch(string sHOWNAME, string uSERREGION, string eMAILADDRESS, string eXCLUSIONS, string nOTIFICATION, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "findShowInMyRegion"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find streaming sites in my region which have the show I want to watch", null, @__tags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "SHOWNAME",
                            "USERREGION",
                            "EMAILADDRESS",
                            "EXCLUSIONS",
                            "NOTIFICATION"});
                table1.AddRow(new string[] {
                            string.Format("{0}", sHOWNAME),
                            string.Format("{0}", uSERREGION),
                            string.Format("{0}", eMAILADDRESS),
                            string.Format("{0}", eXCLUSIONS),
                            string.Format("{0}", nOTIFICATION)});
#line 6
 testRunner.Given("There is a show that I want to watch", ((string)(null)), table1, "Given ");
#line hidden
#line 9
 testRunner.When("I enter the name od the show I want to watch", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 10
 testRunner.Then("A list of sites is presented to me where I can stream the show", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 11
 testRunner.And("my show is added to a notification list so if it leaves or is added to a service " +
                        "I get notified", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CustomerFeaturesFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CustomerFeaturesFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
